name: Build and Deploy
on:
  push:
    branches:
      - developer
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Installing Node js 
        uses: actions/checkout@v2

      - name: JUAN TEST 
        uses: actions/setup-node@v2
        with:
          node-version: '20'
